name: Build and Test Spring Boot App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean verify -DskipTests=false

      - name: Run tests and generate JaCoCo coverage
        run: mvn test jacoco:report

      - name: Upload JaCoCo report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar


      - name: Upload Dockerfile and scripts artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-files
          path: |
            Dockerfile
            mvnw
            pom.xml
            .mvn/**

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file
          path: ./target

      - name: Download deploy files artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-files
          path: ./deploy-files

      - name: List files before upload (debug)
        run: |
          echo "List root files:"
          ls -la
          echo "List target folder:"
          ls -la target
          echo "List deploy-files folder:"
          ls -la deploy-files

      - name: List files before upload
        run: |
           echo "Root directory:"
           ls -la
           echo "target directory:"
           ls -la target || echo "target folder not found"


      - name: Upload app files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            target/CITASalud_Backend.jar
            deploy-files/Dockerfile
            deploy-files/mvnw
            deploy-files/pom.xml
            deploy-files/.mvn/**
          target: "/home/ubuntu/app"

      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/app
            docker stop myapp || true
            docker rm myapp || true
            docker build -t myapp .
            docker run -d -p 8080:8080 --name myapp myapp
