# Nombre del workflow
name: Build and Deploy Spring Boot App

# Evento que dispara el workflow: push o pull request sobre la rama "main"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Primer job: construir la imagen Docker y subirla a Docker Hub
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest  # Usa un runner con Ubuntu

    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura Java 17 (Temurin es la distribución de adoptium)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Usa caché de dependencias de Maven para acelerar builds
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Ejecuta tests y genera el informe de cobertura con JaCoCo
      - name: Run tests and generate JaCoCo coverage
        run: mvn test jacoco:report

      # Sube el reporte de cobertura como artefacto para inspección
      - name: Upload JaCoCo report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      # Ejecuta análisis de calidad de código con SonarCloud
      - name: SonarCloud Scan
        run: mvn verify sonar:sonar -Dsonar.projectKey=Alejo311548_CitaSALUD_Laboratorio_2 -Dsonar.organization=alejo311548 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Instala la herramienta de seguridad Snyk
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Ejecuta análisis de vulnerabilidades con Snyk (fallará si hay paquetes actualizables)
      - name: Run Snyk Security Scan
        run: snyk test --file=pom.xml --package-manager=maven --fail-on=upgradable
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Inicia sesión en Docker Hub usando las credenciales del repositorio
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construye la imagen Docker y la sube al repositorio de Docker Hub
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/citasalud-backend
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  # Segundo job: desplegar en EC2 (se ejecuta solo si el job de build fue exitoso)
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build  # Espera a que termine correctamente el job 'build'

    steps:
      # Se conecta por SSH a la instancia EC2 y ejecuta comandos para actualizar el contenedor
      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/citasalud-backend
            docker pull $IMAGE_NAME:latest
            docker stop citasalud-backend || true  # Detiene el contenedor si está corriendo
            docker rm citasalud-backend || true    # Elimina el contenedor anterior
            docker run -d -p 8080:8080 --name citasalud-backend $IMAGE_NAME:latest  # Inicia el nuevo contenedor
